### ISSUE TITLE
TopView考核的代码改进

### ISSUE THREAD

**Issue by jermyn626** [jermyn626/QG-WebCamp#4]
# Dao层
Dao层中每个方法一般都（Connection con，形参2，…）

# Service层
Service层每个方法一般通过静态方法来获得一个连接，让多个Dao共用。（如果Dao层每个方法都建立一个连接就很费时间）
> ***注意：不要整个业务层用一个静态Connection！！否则会有多线程并发问题。***
![image](https://cloud.githubusercontent.com/assets/18393754/14774775/4f641c10-0aec-11e6-8a12-b7e363a91d57.png)
![image](https://cloud.githubusercontent.com/assets/18393754/14774788/5c52a5ea-0aec-11e6-9a71-79ca5cad199a.png)

# ResultSet
> 是一个数据结果集合，里面装的是数据，生命周期应该限定在dao层方法内，不能返回给上层（Service层），否则有时候忘记关闭连接，会造成资源浪费，因为这些会占用物理资源。

一般用容器封装一个个实体对象，每个实体封装ResultSet每迭代一次的数据，然后返回这个容器（实体集合）给上层即可。

# View层
一般View层只做展示，不要做太多控制层（Dao，Service，Util）的东西（验证，获取数据库连接..都是控制层的事，在View尽量少写这些）。

**Comment by LitterWorn** [comment]
我怎么发现后面是我说的原话，可以多写一下自己的见解
对于service层那个，你理解了嘛？  你知道为什么会发生这种情况，尝试从内存分配的角度去解释这个问题
dao层写的那个我有点看的不是很懂

**Comment by jermyn626** [comment]
Service层那个我从内存分配的角度想明白了，好我再更新，连着Dao层一起解释清晰，写自己的见解

**Comment by LitterWorn** [comment]
修改了可以告诉我，我再看一下😏
